package sklep.services;

import java.io.IOException;
import java.sql.*;
import java.util.*;

import javax.enterprise.context.ApplicationScoped;

import sklep.project.*;


@ApplicationScoped
public class ProductDBManager {

	private Connection conn;
	private Statement stmt;
	private PreparedStatement addProductStmt;
	private PreparedStatement getProductStmt;
	private PreparedStatement deleteAllProductStmt;
	private PreparedStatement findProductByNameStmt;
	private PreparedStatement findProductByTypeStmt;
	private PreparedStatement deleteProductStmt;
	
	List<Integer> listID = new ArrayList<Integer>();
	
	public ProductDBManager() 
	{
		try 
		{
			
			conn = DriverManager
					.getConnection("jdbc:hsqldb:hsql://localhost/workdb");

			stmt = conn.createStatement();
			boolean ProductTableExists = false;

			ResultSet rs = conn.getMetaData().getTables(null, null, null, null);

			while (rs.next()) 
			{
				if ("Product".equalsIgnoreCase(rs.getString("TABLE_NAME"))) 
				{
					ProductTableExists = true;
					break;
				}
			}

			if (!ProductTableExists) 
			{
				stmt.executeUpdate("CREATE TABLE Product(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name varchar(40), alcType varchar(20), releaseYear integer, price integer)");
			}


			addProductStmt = conn.prepareStatement("INSERT INTO Product (name, alcType, releaseYear, price) VALUES (?, ?, ?, ?)");

			getProductStmt = conn.prepareStatement("SELECT * FROM Product");
			
			deleteAllProductStmt = conn.prepareStatement("DELETE FROM Product");
			
			findProductByNameStmt = conn.prepareStatement("SELECT id FROM Product WHERE name = ?");
			
			findProductByTypeStmt = conn.prepareStatement("SELECT id FROM Product WHERE alcType = ?");
			
			deleteProductStmt = conn.prepareStatement("DELETE FROM Product WHERE id = ?");
		} 
		catch (SQLException e) 
		{

			e.printStackTrace();
		}
	}

	public void addProduct(Product Product) 
	{
		try 
		{
			addProductStmt.setString(1, Product.getName());
			addProductStmt.setString(2, Product.getAlcType().toString());
			addProductStmt.setInt(3, Product.getReleaseYear());
			addProductStmt.setInt(4, Product.getPrice());
			addProductStmt.executeUpdate();
		} 
		catch (SQLException e) 
		{

			e.printStackTrace();
		}

	}

	public List<Product> getAllProducts() 
	{
		List<Product> Products = new ArrayList<Product>();
		try 
		{
			ResultSet rs = getProductStmt.executeQuery();
			while (rs.next()) 
			{
				AlcType alcType = null;
				if (rs.getString("alcType").equals("Beer"))
					alcType = AlcType.Beer;
				if (rs.getString("alcType").equals("Brandy"))
					alcType = AlcType.Brandy;
				if (rs.getString("alcType").equals("Liqueur"))
					alcType = AlcType.Liqueur;
				if (rs.getString("alcType").equals("Rum"))
					alcType = AlcType.Rum;
				if (rs.getString("alcType").equals("Vodka"))
					alcType = AlcType.Vodka;
				if (rs.getString("alcType").equals("Whiskey"))
					alcType = AlcType.Whiskey;
				
				Products.add(new Product(rs.getString("name"),alcType,rs.getInt("releaseYear"),rs.getInt("price")));
			}

		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
		return Products;
	}

	public void deleteAllProduct() 
	{
		try 
		{
			deleteAllProductStmt.executeUpdate();
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
	}
	
	public List<Integer> findProductByName(String name)
	{
		try 
		{
			List<Integer> result = new ArrayList<Integer>();
			findProductByNameStmt.setString(1, name);
			ResultSet rs = findProductByNameStmt.executeQuery();
			while (rs.next())
				result.add(rs.getInt("ID"));	
			return result;
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
		return null;
	}
	
	public List<Integer> findProductByType(AlcType alcType)
	{
		try 
		{
			List<Integer> result = new ArrayList<Integer>();
			findProductByTypeStmt.setString(1, alcType.toString());
			ResultSet rs = findProductByTypeStmt.executeQuery();
			while (rs.next())
				result.add(rs.getInt("ID"));
			return result;
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
		return null;
	}
	
	public void deleteProduct(List<Integer> list)
	{
		try 
		{
			for (Integer id : list)
			{
				deleteProductStmt.setInt(1, id);
				deleteProductStmt.executeUpdate();
			}
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
	}
	

	


}
